### ISSUE TITLE
Support Tact 1.5.0

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-vscode#44]
Full changelog for Tact v1.5.0: https://github.com/tact-lang/tact/blob/main/CHANGELOG.md#150---2024-09-15

### New Tact features

- `asm` functions: `asm fun keccak256(s: Slice): Int { 1 INT HASHEXT_KECCAK256 }`;
- Wider range of serialization options for integers — `uint1` through `uint256` and `int1` through `int257`: `counter: Int as uint48`;
- Allow omitting last semicolons in contract/trait declarations and definitions: `trait Test { abstract fun foo() }` -- the semicolon after `foo()` is not required anymore.

### New builtin and stdlib functions and methods

- The `exists` method for the `Map` type: `m.exists(key)`, equivalent to `m.get(key) != null`;
- The `deepEquals` method for the `Map` type: `m1.deepEquals(m2)`;
- The `toSlice` method for structs and messages: `struct.toSlice()`;
- The `storeBit` method for `Builder` type and the `loadBit` method for `Slice` type (aliases for `storeBool` and `loadBool` respectively): `b.storeBit(true)`, `sl.loadBit()`;
- `slice`, `rawSlice`, `ascii` and `crc32` built-in functions;
- Corresponding stdlib functions for the new TVM instructions from 2023.07 and 2024.04 upgrades:  `storeBuilder` extension function and `gasConsumed`, `getComputeFee`, `getStorageFee`, `getForwardFee`, `getSimpleComputeFee`, `getSimpleForwardFee`, `getOriginalFwdFee`, `myStorageDue` functions.
- `Builder.storeMaybeRef`, `parseStdAddress` and `parseVarAddress` stdlib functions.

**Comment by logvik** [comment]
I will try to dedicate next weekend to this...

**Comment by novusnota** [comment]
@logvik As a heads up — the TextMate grammar for 1.5.0 is [completed](https://github.com/tact-lang/tact-sublime/blob/main/package/Tact.tmLanguage.json), so just reuse it :)

**Comment by logvik** [comment]
@novusnota did you include all changes from the checklist to the #45 patch? Just this issue was closed after the merging, but I am not sure on 100% that all needed features were implemented. If yes, that I will close, if no, then let's specify what we should add more.

**Comment by novusnota** [comment]
@logvik yes, I believe:

1. Added all the new global functions (+ some missing ones, like `send()`)
2. Added all the extension functions (`Builder.storeBit()`, etc.)
3. Added new map methods (`.exists()`, `.deepEquals()`) and Struct and Message method `toSlice()`
4. Omitting semicolons in contracts/traits was already there due to ASI of JavaScript (`EOS` rule in pegjs grammar)
5. Wider range of serialization options (`uint1-256`, etc.) was added in the highlighting, while the parser supported any already
6. `asm` functions — both in the parser and in highlighting
